definitions:
  models.Event:
    properties:
      dateTime:
        type: string
      description:
        type: string
      id:
        type: integer
      location:
        type: string
      name:
        type: string
      userId:
        type: integer
    required:
    - dateTime
    - description
    - location
    - name
    type: object
info:
  contact: {}
paths:
  /events:
    get:
      consumes:
      - application/json
      description: Get all the events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: all events
    post:
      consumes:
      - application/json
      description: Create a new event
      parameters:
      - description: models.Event
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: ""
      summary: create event
  /events/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a single event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: delete event
    get:
      consumes:
      - application/json
      description: Get a single event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: single event
    put:
      parameters:
      - description: token
        in: header
        name: event
        required: true
        type: string
      - description: models.Event
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      responses:
        "200":
          description: OK
          schema:
            type: ""
  /events/{id}/register:
    delete:
      consumes:
      - application/json
      description: Cancel registration for an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: cancel registration
    post:
      consumes:
      - application/json
      description: Register for an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: register for event
  /login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: email
        in: path
        name: email
        required: true
        type: string
      - description: password
        in: path
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: login
  /signup:
    post:
      consumes:
      - application/json
      description: Register for an event
      parameters:
      - description: email
        in: path
        name: email
        required: true
        type: string
      - description: password
        in: path
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: ""
      summary: register for event
swagger: "2.0"
